name: Publish Docker Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
             COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
             docker build --file Dockerfile --tag ghcr.io/0xportal/website .
    - name: Upload the Docker image
      run: |
             echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username 0xportal --password-stdin
             docker push ghcr.io/0xportal/todo:latest
